name: Deploy Website
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file infrastructure/template.yaml \
          --stack-name cloudpipe-deploy-stack \
          --capabilities CAPABILITY_IAM
    
    - name: Upload to S3
      run: |
        aws s3 sync website/ s3://cloudpipe-deploy-${{ secrets.AWS_ACCOUNT_ID }}/ \
          --delete
    
    - name: Notify Completion
      if: always()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel-id: 'deploy-notifications'
        text: "Website deployment completed. Status: ${{ job.status }}"